# Generated by Django 5.2.15 on 2026-07-09 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0018_add_filter_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_absence', models.CharField(choices=[('0971', 'APLD'), ('0951', 'CP'), ('0950', 'RTT'), ('2000', 'Maladie'), ('2020', 'Accident du travail'), ('1000', 'Maladie professionnelle'), ('2010', 'Maternité'), ('2040', 'Paternité'), ('0990', 'Événement familial'), ('0991', 'Enfant malade'), ('0981', 'Congé sans solde'), ('0978', 'Absence justifiée et payée'), ('0977', 'Absence non rémunérée'), ('0974', 'Grève'), ('1040', 'Accident de trajet'), ('0979', 'Absence injustifiée')], max_length=4)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('demi_journee', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='en_attente', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='CompteurRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_cp_pris', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('solde_cp_prevu', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('solde_rtt', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rtt_max_annuel', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date_derniere_maj', models.DateField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compteur_rh', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PosteTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postes_travail', to='users.site')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CycleHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('structure', models.JSONField(default=dict)),
                ('type_organisation', models.CharField(choices=[('jour', 'Jour'), ('equipe', 'Équipe'), ('nuit', 'Nuit')], max_length=10)),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles_horaires', to='evp.postetravail')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='evp.cyclehoraire')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='evp.postetravail')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='PrimeCalculee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_prime', models.CharField(choices=[('CL30', 'Nombre de paniers jours'), ('CL31', 'Nombre de paniers nuits'), ('CL06', "Prime d'exploitation"), ('CL11', 'Prime de nuit'), ('CL16', "Prime d'astreinte"), ('CL01', 'Majoration heures de nuit 25%'), ('HS01', 'Heures supplémentaires 125%'), ('HS02', 'Heures supplémentaires 150%')], max_length=4)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quantite', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primes_calculees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='JourTravaille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heures_travaillees', models.DecimalField(decimal_places=2, max_digits=5)),
                ('organisation', models.CharField(choices=[('jour', 'Jour'), ('equipe', 'Équipe'), ('nuit', 'Nuit')], max_length=10)),
                ('heures_nuit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('heures_sup_payees', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('heures_sup_recuperees', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jours_travailles', to=settings.AUTH_USER_MODEL)),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jours_travailles', to='evp.postetravail')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='unique_jour_travaille_par_employee')],
            },
        ),
    ]
