# Generated by Django 5.2.15 on 2026-07-09 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('evp', '0001_initial'),
        ('users', '0018_add_filter_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jourtravaille',
            name='heures_nuit',
        ),
        migrations.RemoveField(
            model_name='jourtravaille',
            name='heures_travaillees',
        ),
        migrations.RemoveField(
            model_name='primecalculee',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='primecalculee',
            name='quantite',
        ),
        migrations.AddField(
            model_name='compteurrh',
            name='ajustement_manuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='jourtravaille',
            name='heures_nuit_calcule',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='jourtravaille',
            name='heures_nuit_modifie_manuellement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jourtravaille',
            name='heures_nuit_motif_modification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jourtravaille',
            name='heures_nuit_retenu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='jourtravaille',
            name='heures_travaillees_calcule',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='jourtravaille',
            name='heures_travaillees_modifie_manuellement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jourtravaille',
            name='heures_travaillees_motif_modification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jourtravaille',
            name='heures_travaillees_retenu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='primecalculee',
            name='modifie_manuellement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='primecalculee',
            name='montant_calcule',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='primecalculee',
            name='montant_retenu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='primecalculee',
            name='motif_modification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='primecalculee',
            name='quantite_calcule',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='primecalculee',
            name='quantite_retenu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='code_absence',
            field=models.CharField(choices=[('0971', 'APLD'), ('0951', 'Congé payé'), ('0950', 'RTT'), ('2000', 'Maladie'), ('2020', 'Accident du travail'), ('1000', 'Maladie professionnelle'), ('2010', 'Maternité'), ('2040', 'Paternité'), ('0990', 'Événement familial'), ('0991', 'Enfant malade'), ('0981', 'Congé sans solde'), ('0978', 'Absence justifiée et payée'), ('0977', 'Absence non rémunérée'), ('0974', 'Grève'), ('1040', 'Accident de trajet'), ('0979', 'Absence injustifiée')], max_length=4),
        ),
        migrations.AlterField(
            model_name='cyclehoraire',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles_horaires', to='evp.postetravail'),
        ),
        migrations.CreateModel(
            name='CorrectionManuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('champ_modifie', models.CharField(max_length=100)),
                ('ancienne_valeur', models.CharField(blank=True, max_length=255)),
                ('nouvelle_valeur', models.CharField(blank=True, max_length=255)),
                ('motif', models.TextField()),
                ('corrige_le', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('corrige_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections_manuelles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-corrige_le'],
            },
        ),
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jours_feries', to='users.site')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ClotureMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('statut', models.CharField(choices=[('draft', 'Brouillon'), ('cloture', 'Clôturé')], default='draft', max_length=10)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('cloture_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures_effectuees', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clotures_mensuelles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-annee', '-mois'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'mois', 'annee'), name='unique_cloture_par_employee_mois')],
            },
        ),
    ]
