# Generated by Django 5.2.15 on 2026-07-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evp', '0002_calcule_retenu_pattern_and_cloture'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteurrh',
            name='dernier_annee_rtt_creditee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compteurrh',
            name='dernier_mois_rtt_credite',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
