# Generated by Django 5.2.15 on 2026-07-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_augmentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fonctionnement',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='niveau',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
