# Generated by Django 5.2.15 on 2026-07-09 07:05

import apps.users.models
from django.db import migrations, models


def make_admin_role_users_superusers(apps, schema_editor):
    """Existing rows with role=admin must become real superusers before
    the role_admin_requires_superuser constraint can be added."""
    User = apps.get_model("users", "User")
    User.objects.filter(role="admin", is_superuser=False).update(is_superuser=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0014_add_niveau_fonctionnement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
        migrations.RunPython(make_admin_role_users_superusers, noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'admin'), _negated=True), ('is_superuser', True), _connector='OR'), name='role_admin_requires_superuser'),
        ),
    ]
