# Generated by Django 5.2.15 on 2026-07-09 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_admin_role_requires_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evolution', models.CharField(choices=[('poste', 'Poste'), ('service', 'Service'), ('site', 'Site'), ('statut', 'Statut'), ('niveau', 'Niveau'), ('coefficient', 'Coefficient'), ('salaire', 'Salaire')], max_length=20)),
                ('ancienne_valeur', models.CharField(blank=True, max_length=255)),
                ('nouvelle_valeur', models.CharField(blank=True, max_length=255)),
                ('date_effet', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolutions_creees', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_effet', '-created_at'],
            },
        ),
    ]
