# Generated by Django 5.2.15 on 2026-07-09 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_evolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='augmentation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='augmentations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evolution',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formations', to=settings.AUTH_USER_MODEL),
        ),
    ]
