# Generated by Django 5.2.15 on 2026-07-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_protect_history_employee_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_sortie',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('rh', 'RH'), ('manager', 'Manager'), ('employee', 'Employé'), ('stagiaire', 'Stagiaire'), ('alternant', 'Alternant')], db_index=True, default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('sortie', 'Sortie')], db_index=True, default='actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_contrat',
            field=models.CharField(blank=True, choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('interim', 'Intérim'), ('alternance', 'Alternance'), ('stage', 'Stage')], db_index=True, max_length=20),
        ),
    ]
