# Generated by Django 5.2.15 on 2026-07-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_add_filter_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_badge',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager_evp',
            field=models.BooleanField(default=False),
        ),
    ]
