# Generated by Django 5.2.15 on 2026-07-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_code_badge_user_is_manager_evp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code_badge',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_manager_evp',
        ),
    ]
