# Generated by Django 5.2.15 on 2026-07-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_user_code_badge_remove_user_is_manager_evp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categorie_socio_pro',
            field=models.CharField(blank=True, choices=[('ouvrier', 'Ouvrier'), ('agent_maitrise', 'Agent de maîtrise'), ('cadre', 'Cadre')], db_index=True, max_length=20),
        ),
    ]
