# Generated by Django 5.2.15 on 2026-07-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_categorie_socio_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='matricule',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
