# Generated by Django 5.2.15 on 2026-07-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0008_alter_interview_type_alter_interviewtemplate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='template_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
