# Generated by Django 5.2.15 on 2026-07-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0011_alter_interview_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('signed', 'Signé'), ('cancelled', 'Annulé')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='interview',
            name='type',
            field=models.CharField(choices=[('annual', "Entretien d'évaluation"), ('professional', 'Entretien professionnel'), ('bilan', 'Entretien de bilan'), ('forfait', 'Entretien forfait jours et charges'), ('fin_carriere', 'Entretien de fin de carrière')], db_index=True, max_length=20),
        ),
    ]
