# Generated by Django 5.2.15 on 2026-07-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0012_add_filter_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='date_realisation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
